"""Create job and task and dataprocessing tables

Revision ID: 62fcea0a58f1
Revises: 4f9e2e60f7b9
Create Date: 2024-08-01 12:31:00.930111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fcea0a58f1'
down_revision = '4f9e2e60f7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
